# Generated by Django 5.2 on 2026-03-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.EmailField(default='anonymous@gmail.com', max_length=254),
        ),
    ]
